version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/code

  postgres:
    build: ./postgres
    ports:
    - 5432
    volumes:
    - ./postgres/data:/var/lib/postgresql/data

  redis:
    build: ./redis

  php-fpm:
    build: ./php/php-fpm
    volumes:
      - ./src:/code

  php-cli:
    build: ./php/php-cli
    volumes:
      - ./src:/code
    depends_on:
      - postgres
    command: sh -c 'wait-for-it postgres:5432 -- sleep 5 && php artisan migrate:fresh --seed && tail -f /dev/null'

  composer:
    build: ./php/composer
    volumes:
      - ./src:/code
    working_dir: /code